### ISSUE TITLE
jekyll 2.1.1 | Error:  uninitialized constant Jekyll::Pager

### ISSUE THREAD

**Issue by mlundela** [prometheus-ev/jekyll-rendering#1]
It seems that the current version is not compatible with jekyll 2.1.1

```
mac:nnl-website Mads$ jekyll build -t
Configuration file: /Users/Mads/work/nnl-website/_config.yml
/Library/Ruby/Gems/2.0.0/gems/jekyll-rendering-0.0.9/lib/jekyll/rendering.rb:289:in `<module:Jekyll>': uninitialized constant Jekyll::Pager (NameError)
from /Library/Ruby/Gems/2.0.0/gems/jekyll-rendering-0.0.9/lib/jekyll/rendering.rb:37:in `<top (required)>'
from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from /Library/Ruby/Gems/2.0.0/gems/jekyll-localization-0.1.7/lib/jekyll/localization.rb:35:in `<top (required)>'
from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:128:in `require'
from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:39:in `require'
from /Users/Mads/work/nnl-website/_plugins/ext.rb:1:in `<top (required)>'
from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.1.1/lib/jekyll/plugin_manager.rb:58:in `block (2 levels) in require_plugin_files'
from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.1.1/lib/jekyll/plugin_manager.rb:57:in `each'
from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.1.1/lib/jekyll/plugin_manager.rb:57:in `block in require_plugin_files'
from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.1.1/lib/jekyll/plugin_manager.rb:56:in `each'
from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.1.1/lib/jekyll/plugin_manager.rb:56:in `require_plugin_files'
from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.1.1/lib/jekyll/plugin_manager.rb:18:in `conscientious_require'
from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.1.1/lib/jekyll/site.rb:71:in `setup'
from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.1.1/lib/jekyll/site.rb:33:in `initialize'
from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.1.1/lib/jekyll/commands/build.rb:28:in `new'
from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.1.1/lib/jekyll/commands/build.rb:28:in `process'
from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.1.1/lib/jekyll/commands/build.rb:17:in `block (2 levels) in init_with_program'
from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `call'
from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `block in execute'
from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `each'
from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.4/lib/mercenary/command.rb:220:in `execute'
from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.4/lib/mercenary/program.rb:35:in `go'
from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.4/lib/mercenary.rb:22:in `program'
from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.1.1/bin/jekyll:18:in `<top (required)>'
from /usr/bin/jekyll:23:in `load'
from /usr/bin/jekyll:23:in `<main>'
```

**Comment by efung** [comment]
`Pager` was moved to the `jekyll-paginate` gem as of [Jekyll 2.1.0](http://jekyllrb.com/docs/history/#v2-1-0). So references to `Pager` should now be `Jekyll::Paginate::Pager`.
